name: 'buf-lint'
description: >
  Check that the Input location passes lint checks.
branding:
  icon: alert-circle
  color: blue
inputs:
  # The definition of an input can be found in the following:
  # https://docs.buf.build/inputs#specifying-an-input
  input:
    description: 'The input path.'
    default: '.'
  buf_token:
    description: 'The buf authentication token used for private inputs.'
runs:
  using: 'node12'
  main: './dist/main.js'
